import Link from "next/link";
import { ArrowRight, CircleDollarSign, Clock3, Sparkles, TrendingUp } from "lucide-react";
import { MetricCard } from "@/components/dashboard/metric-card";
import { OpportunityTable } from "@/components/opportunities/opportunity-table";
import { RevenueChart } from "@/components/dashboard/revenue-chart";
import { PageHeader } from "@/components/ui/page-header";
import { requireSessionIdentity } from "@/server/auth/session";
import { getDashboardData } from "@/server/repositories/dashboard";
export default async function DashboardPage() { const s = await requireSessionIdentity(); const d = await getDashboardData(s.workspaceId); const first = s.userName.split(/\s+/)[0] || s.userName; const metrics = [{ label: "Qualified pipeline", value: d.metrics.qualifiedPipeline, delta: "Open commercial value" }, { label: "Won", value: d.metrics.wonThisMonth, delta: "Accepted value" }, { label: "Collected", value: d.metrics.collected, delta: "Verified settlements" }, { label: "Follow-ups due", value: d.metrics.followUpsDue, delta: `${d.metrics.highPriority} high priority`, count: true }]; return <><PageHeader eyebrow="Workspace overview" title={`Good afternoon, ${first}.`} description="A focused view of money in motion, buyer intent and what needs your attention next." action={<Link className="button button--primary" href="/opportunities"><Sparkles size={16}/>Review pipeline</Link>}/><div className="metric-grid">{metrics.map(m => <MetricCard key={m.label} {...m}/>)}</div><div className="dashboard-grid dashboard-grid--hero"><section className="surface chart-card"><div className="section-heading"><div><span className="eyebrow">Collected revenue</span><h2>Settlement momentum</h2></div><span className="trend-label"><TrendingUp size={14}/>Verified only</span></div><RevenueChart data={d.revenueSeries.length ? d.revenueSeries : [{ label: "Now", revenue: 0 }]}/></section><section className="surface activity-card"><div className="section-heading"><div><span className="eyebrow">Operator inbox</span><h2>Latest changes</h2></div></div><div className="activity-list">{d.activities.map(item => <div className="activity-item" key={item.id}><div className="activity-icon">{item.type.includes("PAYMENT") ? <CircleDollarSign size={16}/> : <Clock3 size={16}/>}</div><div><strong>{item.summary}</strong><span>{item.actor ?? "System"}</span></div><time>{item.createdAt.toLocaleDateString("en", { month: "short", day: "numeric" })}</time></div>)}</div></section></div><section className="surface pipeline-surface"><div className="section-heading"><div><span className="eyebrow">Priority queue</span><h2>Best opportunities to move today</h2></div><Link className="text-link" href="/opportunities">View pipeline <ArrowRight size={14}/></Link></div><OpportunityTable rows={d.priority} limit={4}/></section></>; }
